// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4wfwt8rOxym2LNRNxtA22raGp2dnvuHk',
    appId: '1:507020516427:web:eea583d546a3be5a8c41ce',
    messagingSenderId: '507020516427',
    projectId: 'appfinal-7e219',
    authDomain: 'appfinal-7e219.firebaseapp.com',
    storageBucket: 'appfinal-7e219.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6A37Ln17JWoBdsDVsyHCGGG8i7VjBDQ',
    appId: '1:507020516427:android:23ccba59bdb768bb8c41ce',
    messagingSenderId: '507020516427',
    projectId: 'appfinal-7e219',
    storageBucket: 'appfinal-7e219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWgbi_SUIMhY6I1ChKGji4FrD0ZC9dYdQ',
    appId: '1:507020516427:ios:3319a20c549653878c41ce',
    messagingSenderId: '507020516427',
    projectId: 'appfinal-7e219',
    storageBucket: 'appfinal-7e219.appspot.com',
    iosBundleId: 'com.example.lembrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWgbi_SUIMhY6I1ChKGji4FrD0ZC9dYdQ',
    appId: '1:507020516427:ios:f91456e521400ef28c41ce',
    messagingSenderId: '507020516427',
    projectId: 'appfinal-7e219',
    storageBucket: 'appfinal-7e219.appspot.com',
    iosBundleId: 'com.example.lembrol.RunnerTests',
  );
}
